version: '3.7'
services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  backend:
    image: evgen1000end/config-server:1.0.0
    ports:
      - 8080:8080