app:
  auth-enabled: true

spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

mybatis:
  config-location: classpath:mybatis.xml

server:
  port: 8080

  error:
    whitelabel:
      enabled: false


